[package]
name = "day15-2"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
neure = { git = "https://github.com/araraloren/neure", branch = "v0.4", version = "0.4.0" }